### ISSUE TITLE
java.lang.NoSuchMethodError: com.epam.reportportal.utils.TestCaseIdUtils.getTestCaseId

### ISSUE THREAD

**Issue by deepakarorawins** [reportportal/client-java#172]
agent-java-testng: - 5.0.7
testng:  - 7.0.1

The agent works up to Before Method, and after that on test start that it fails with the following message: - 

> FAILED: loginWithValidCredentials
java.lang.NoSuchMethodError: com.epam.reportportal.utils.TestCaseIdUtils.getTestCaseId(Lcom/epam/reportportal/annotations/TestCaseId;Ljava/lang/reflect/Method;Ljava/util/List;)Lcom/epam/reportportal/service/item/TestCaseIdEntry;
	at com.epam.reportportal.testng.TestNGService.lambda$getTestCaseId$21(TestNGService.java:795)
	at java.util.Optional.map(Optional.java:215)
	at com.epam.reportportal.testng.TestNGService.getTestCaseId(TestNGService.java:795)
	at com.epam.reportportal.testng.TestNGService.buildStartStepRq(TestNGService.java:327)
	at com.epam.reportportal.testng.TestNGService.startTestMethod(TestNGService.java:356)
	at com.epam.reportportal.testng.BaseTestNGListener.onTestStart(BaseTestNGListener.java:82)
	at org.testng.internal.TestListenerHelper.runTestListeners(TestListenerHelper.java:73)
	at org.testng.internal.TestInvoker.runTestResultListener(TestInvoker.java:219)
	at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:570)
	at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
	at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
	at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
	at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
===============================================
    BVT
    Tests run: 1, Failures: 1, Skips: 0
===============================================

 
Could you please advice what is wrong here ?

**Comment by HardNorth** [comment]
You are using old version of `client-java` module, please don't specify it manually use transitive dependencies. Or you use old version of a logger which forces to use old version of `client-java`.
