### ISSUE TITLE
java.lang.NoClassDefFoundError: com/epam/reportportal/service/LockFile$5 when running as junit standalone

### ISSUE THREAD

**Issue by willyhalim** [reportportal/client-java#194]
Issue when running test using junit-platform-console-standalone.jar

```
Exception in thread "Thread-1" java.lang.NoClassDefFoundError: com/epam/reportportal/service/LockFile$5
        at com.epam.reportportal.service.LockFile.finishInstanceUuid(LockFile.java:275)
        at com.epam.reportportal.service.ReportPortal$PrimaryLaunch.finish(ReportPortal.java:539)
        at com.epam.reportportal.junit5.ReportPortalExtension.lambda$getShutdownHook$19(ReportPortalExtension.java:415)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassNotFoundException: com.epam.reportportal.service.LockFile$5
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at java.net.FactoryURLClassLoader.loadClass(URLClassLoader.java:814)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 4 more
```
The above not appearing if we run as part of mvn install

After further investigation seems this issue triggered by the shutdown hook in ReportPortalExtension

```
private static Thread getShutdownHook(Launch launch) {
    return new Thread(() -> {
        FinishExecutionRQ rq = new FinishExecutionRQ();
        rq.setEndTime(Calendar.getInstance().getTime());
        launch.finish(rq);
    });
}

```

1. package the whole project as a fat jar
2. run java -jar junit-platform-console-standalone.jar -cp $CLASSPATH --scan-classpath

Version of Client-Java

```
 <dependency>
            <groupId>com.epam.reportportal</groupId>
            <artifactId>client-java</artifactId>
            <version>5.0.0-BETA-9</version>
        </dependency>

<dependency>
            <groupId>com.epam.reportportal</groupId>
            <artifactId>agent-java-junit5</artifactId>
            <version>5.0.0-BETA-9</version>
        </dependency>

```

**Comment by HardNorth** [comment]
@willyhalim There is no one-on-one mapping of agent and client versions. Please use transient dependency. And BTW you are using very old version of the agent.
