### ISSUE TITLE
java.lang.IncompatibleClassChangeError

### ISSUE THREAD

**Issue by qakart** [reportportal/client-java#22]
I am trying to use scala agent but getting the below exception 

Exception in thread "ScalaTest-dispatcher" java.lang.IncompatibleClassChangeError: Expected static method com.epam.reportportal.utils.properties.PropertiesLoader.getProperties()Ljava/util/Properties;
	at com.epam.reportportal.guice.ReportPortalClientModule.configure(ReportPortalClientModule.java:63)
	at com.google.inject.spi.Elements$RecordingBinder.install(Elements.java:223)
	at com.google.inject.spi.Elements.getElements(Elements.java:101)
	at com.google.inject.internal.InjectorShell$Builder.build(InjectorShell.java:133)
	at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:103)
	at com.google.inject.Guice.createInjector(Guice.java:95)
	at com.google.inject.Guice.createInjector(Guice.java:72)
	at com.google.inject.Guice.createInjector(Guice.java:62)
	at com.epam.reportportal.guice.BaseInjector.<init>(BaseInjector.java:61)
	at com.epam.reportportal.guice.Injector.<init>(Injector.java:60)
	at com.epam.reportportal.guice.Injector.<init>(Injector.java:34)
	at com.epam.reportportal.guice.Injector$1.get(Injector.java:44)
	at com.epam.reportportal.guice.Injector$1.get(Injector.java:40)
	at com.google.common.base.Suppliers$MemoizingSupplier.get(Suppliers.java:125)
	at com.epam.reportportal.guice.Injector.getInstance(Injector.java:53)
	at com.epam.reportportal.scalatest.RPReporter$$anon$1.get(RPReporter.scala:53)
	at com.epam.reportportal.scalatest.RPReporter$$anon$1.get(RPReporter.scala:52)
	at com.google.common.base.Suppliers$MemoizingSupplier.get(Suppliers.java:125)
	at com.epam.reportportal.scalatest.RPReporter.apply(RPReporter.scala:77)
	at org.scalatest.DispatchReporter$Propagator.$anonfun$run$10(DispatchReporter.scala:249)
	at org.scalatest.DispatchReporter$Propagator.$anonfun$run$10$adapted(DispatchReporter.scala:248)
	at scala.collection.immutable.List.foreach(List.scala:389)
	at org.scalatest.DispatchReporter$Propagator.run(DispatchReporter.scala:248)
	at java.lang.Thread.run(Thread.java:748)

**Comment by qakart** [comment]
@avarabyeu @pbortnik I am using  client-java 4.0.9 and client-java-core2.7.1 
thanks in advance

**Comment by qakart** [comment]
@evjlobanova  do you think any of your team will help us 
karthik
Expedia

**Comment by evjlobanova** [comment]
Hrllo, @qakart! Unfortunetlly in our team we don`t have any Scala contributors. You can ask this question in our slack channel https://reportportal.slack.com/messages/C2GTJTTNH

**Comment by qakart** [comment]
Thanks a lot @evjlobanova  but i don't have access to that workspace i have tired my Expedia login as well
