### ISSUE TITLE
Error 'Cannot instantiate class com.epam.reportportal.testng.ReportPortalTestNGListener'

### ISSUE THREAD

**Issue by Magesh-3041** [reportportal/client-java#237]
My report portal instance is up and running on docker. I just upgraded the java version from 11 to 17. Now, I couldn't contact RP instance, it is throwing 'Cannot instantiate class com.epam.reportportal.testng.ReportPortalTestNGListener' error.

**Dependency versions**
agent-java-testng - 5.4.1
logger-java-logback - 5.2.1

**Stack Trace**
[RemoteTestNG] detected TestNG version 7.9.0
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
org.testng.TestNGException: 
Cannot instantiate class com.epam.reportportal.testng.ReportPortalTestNGListener
	at org.testng.internal.objects.InstanceCreator.newInstance(InstanceCreator.java:41)
	at org.testng.internal.objects.InstanceCreator.newInstance(InstanceCreator.java:59)
	at org.testng.ITestObjectFactory.newInstance(ITestObjectFactory.java:10)
	at org.testng.internal.objects.SimpleObjectDispenser.dispense(SimpleObjectDispenser.java:60)
	at org.testng.internal.objects.GuiceBasedObjectDispenser.dispense(GuiceBasedObjectDispenser.java:28)
	at org.testng.TestNG.addListeners(TestNG.java:1034)
	at org.testng.TestNG.initializeConfiguration(TestNG.java:991)
	at org.testng.TestNG.initializeEverything(TestNG.java:1082)
	at org.testng.remote.support.RemoteTestNG7_9.initialize(RemoteTestNG7_9.java:24)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:98)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
	at org.testng.internal.objects.InstanceCreator.newInstance(InstanceCreator.java:38)
	... 11 more
Caused by: java.lang.IllegalArgumentException: API interfaces must not extend other interfaces.
	at retrofit2.Utils.validateServiceInterface(Utils.java:334)
	at retrofit2.Retrofit.create(Retrofit.java:131)
	at com.epam.reportportal.service.ReportPortal$Builder.lambda$buildClient$2(ReportPortal.java:457)
	at java.base/java.util.Optional.map(Optional.java:260)
	at com.epam.reportportal.service.ReportPortal$Builder.buildClient(ReportPortal.java:457)
	at com.epam.reportportal.service.ReportPortal$Builder.build(ReportPortal.java:432)
	at com.epam.reportportal.testng.ReportPortalTestNGListener.lambda$static$0(ReportPortalTestNGListener.java:32)
	at com.epam.reportportal.utils.MemoizingSupplier.get(MemoizingSupplier.java:47)
	at com.epam.reportportal.testng.ReportPortalTestNGListener.<init>(ReportPortalTestNGListener.java:35)
	... 17 more

**Comment by Magesh-3041** [comment]
Is RP client-java compatible with only Java 11?

**Comment by HardNorth** [comment]
@Magesh-3041 
As I answered you in Slack:
This is nothing to do with Java version. It fails on interface validation:
```
Caused by: java.lang.IllegalArgumentException: API interfaces must not extend other interfaces.
at retrofit2.Utils.validateServiceInterface(Utils.java:334)
```
This code was in Retrofit (our API client library) till version 2.6.4:
https://github.com/square/retrofit/blob/parent-2.6.4/retrofit/src/main/java/retrofit2/Utils.java#L334
But ReportPortal client supposed to work with Retrofit version starting from 2.7, where interface extension was allowed. Please examine your dependencies and update Retrofit library version. (edited)

**Comment by Magesh-3041** [comment]
Thanks @HardNorth You're right. I was using retrofit v2.6.2 in my project. Upgraded to the latest version and the error resolved. Thanks again for the help. Appreciate it.
