### ISSUE TITLE
ReportPortal fails in "open/enabled" state when properties file does NOT exist

### ISSUE THREAD

**Issue by sspieker-cc** [reportportal/client-java#57]
Although the issue being reported here is specific to the behavior within the JUnit Agent, I believe that the issue is specifically related to the PropertiesLoader.java class as a part of the client-java project.  

We have 300+ java projects, of which, we do not want to maintain reportportal properties within every project and force developers to constantly update the UUID values locally.  Maintenance overhead on every project is the major concern and the primary reason for this issue and enhancement request finding.

By default, we would like the report portal reporting features to be disabled (yes, this can easily be accomplished with the use of the rp.enabled=false property), however, we do not want to have every build that a developer executes on their local machine to be logged either.  Therefore, we are enabling the feature within Jenkins only, writing the reportportal.properties file to the correct location with the appropriate derived values contained within.  The Jenkins process works as expected.  Right now, we have conditions of failing builds if the properties file is missing.

The properties loader class will **NOT** read JVM parameters or ENV vars **UNLESS** the properties file is read first **AND** the property existed within the properties file.  The desired behavior is to allow the build to continue without failing due to misconfiguration or intentional removal of the properties file.

The desired behavior is to have reportportal disabled by default (meaning that the rp.enabled=false) and if the properties file is not present then the process should be skipped / ignored entirely.

Developer local gradle builds fail when the properties file does not exist or does not have appropriate values with:

```
`> Task :test
log4j:WARN No appenders could be found for logger (com.epam.reportportal.service.ReportPortal).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
Exception in thread "main" java.util.ServiceConfigurationError: com.nordstrom.automation.junit.ShutdownListener: Provider com.epam.reportportal.junit.ReportPortalListener could not be instantiated
        at java.util.ServiceLoader.fail(ServiceLoader.java:232)
        at java.util.ServiceLoader.access$100(ServiceLoader.java:185)
        at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:384)
        at java.util.ServiceLoader$LazyIterator.next(ServiceLoader.java:404)
        at java.util.ServiceLoader$1.next(ServiceLoader.java:480)
        at com.nordstrom.automation.junit.LifecycleHooks.<clinit>(LifecycleHooks.java:45)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:386)
        at sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:401)
Caused by: java.lang.ExceptionInInitializerError
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at java.lang.Class.newInstance(Class.java:442)
        at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:380)
        ... 9 more
Caused by: com.google.inject.CreationException: Unable to create injector, see the following errors:

1) Error in custom provider, java.lang.NullPointerException
  while locating com.epam.reportportal.junit.JUnitProvider
  at com.epam.reportportal.junit.JUnitListenersModule.configure(JUnitListenersModule.java:31)
  while locating com.epam.reportportal.junit.IListenerHandler
Caused by: java.lang.NullPointerException
        at com.epam.reportportal.junit.JUnitProvider.get(JUnitProvider.java:44)
        at com.epam.reportportal.junit.JUnitProvider.get(JUnitProvider.java:30)
FATAL ERROR in native method: processing of -javaagent failed
        at com.google.inject.internal.ProviderInternalFactory.provision(ProviderInternalFactory.java:81)
        at com.google.inject.internal.BoundProviderFactory.provision(BoundProviderFactory.java:72)
        at com.google.inject.internal.ProviderInternalFactory.circularGet(ProviderInternalFactory.java:61)
        at com.google.inject.internal.BoundProviderFactory.get(BoundProviderFactory.java:62)
        at com.google.inject.internal.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:46)
        at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1092)
        at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
        at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:194)
        at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:41)
        at com.google.inject.internal.InternalInjectorCreator$1.call(InternalInjectorCreator.java:205)
        at com.google.inject.internal.InternalInjectorCreator$1.call(InternalInjectorCreator.java:199)
        at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1085)
        at com.google.inject.internal.InternalInjectorCreator.loadEagerSingletons(InternalInjectorCreator.java:199)
        at com.google.inject.internal.InternalInjectorCreator.injectDynamically(InternalInjectorCreator.java:180)
        at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:110)
        at com.google.inject.Guice.createInjector(Guice.java:99)
        at com.google.inject.Guice.createInjector(Guice.java:73)
        at com.google.inject.Guice.createInjector(Guice.java:62)
        at com.epam.reportportal.junit.JUnitInjectorProvider$1.get(JUnitInjectorProvider.java:36)
        at com.epam.reportportal.junit.JUnitInjectorProvider$1.get(JUnitInjectorProvider.java:33)
        at com.google.common.base.Suppliers$NonSerializableMemoizingSupplier.get(Suppliers.java:167)
        at com.epam.reportportal.junit.JUnitInjectorProvider.getInstance(JUnitInjectorProvider.java:41)
        at com.epam.reportportal.junit.ReportPortalListener.<clinit>(ReportPortalListener.java:45)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at java.lang.Class.newInstance(Class.java:442)
        at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:380)
        at java.util.ServiceLoader$LazyIterator.next(ServiceLoader.java:404)
        at java.util.ServiceLoader$1.next(ServiceLoader.java:480)
        at com.nordstrom.automation.junit.LifecycleHooks.<clinit>(LifecycleHooks.java:45)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:386)
        at sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:401)
```

2) Error injecting method, com.epam.reportportal.exception.InternalReportPortalClientException: 
```java
Cannot build ReportPortal client
  at com.epam.reportportal.junit.JUnitProvider.setReportPortalService(JUnitProvider.java:39)
  while locating com.epam.reportportal.junit.JUnitProvider
  at com.epam.reportportal.junit.JUnitListenersModule.configure(JUnitListenersModule.java:31)
  while locating com.epam.reportportal.junit.IListenerHandler
Caused by: com.epam.reportportal.exception.InternalReportPortalClientException: Cannot build ReportPortal client
        at com.epam.reportportal.service.ReportPortal$Builder.build(ReportPortal.java:250)
        at com.epam.reportportal.junit.JUnitProvider.setReportPortalService(JUnitProvider.java:39)
        at com.epam.reportportal.junit.JUnitProvider$$FastClassByGuice$$c0d4f1fb.invoke(<generated>)
        at com.google.inject.internal.SingleMethodInjector$1.invoke(SingleMethodInjector.java:54)
        at com.google.inject.internal.SingleMethodInjector.inject(SingleMethodInjector.java:89)
        at com.google.inject.internal.MembersInjectorImpl.injectMembers(MembersInjectorImpl.java:132)
        at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:120)
        at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:90)
        at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:268)
        at com.google.inject.internal.BoundProviderFactory.get(BoundProviderFactory.java:61)
        at com.google.inject.internal.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:46)
        at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1092)
        at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
        at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:194)
        at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:41)
        at com.google.inject.internal.InternalInjectorCreator$1.call(InternalInjectorCreator.java:205)
        at com.google.inject.internal.InternalInjectorCreator$1.call(InternalInjectorCreator.java:199)
        at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1085)
        at com.google.inject.internal.InternalInjectorCreator.loadEagerSingletons(InternalInjectorCreator.java:199)
        at com.google.inject.internal.InternalInjectorCreator.injectDynamically(InternalInjectorCreator.java:180)
        at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:110)
        at com.google.inject.Guice.createInjector(Guice.java:99)
        at com.google.inject.Guice.createInjector(Guice.java:73)
        at com.google.inject.Guice.createInjector(Guice.java:62)
        at com.epam.reportportal.junit.JUnitInjectorProvider$1.get(JUnitInjectorProvider.java:36)
        at com.epam.reportportal.junit.JUnitInjectorProvider$1.get(JUnitInjectorProvider.java:33)
        at com.google.common.base.Suppliers$NonSerializableMemoizingSupplier.get(Suppliers.java:167)
        at com.epam.reportportal.junit.JUnitInjectorProvider.getInstance(JUnitInjectorProvider.java:41)
        at com.epam.reportportal.junit.ReportPortalListener.<clinit>(ReportPortalListener.java:45)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at java.lang.Class.newInstance(Class.java:442)
        at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:380)
        at java.util.ServiceLoader$LazyIterator.next(ServiceLoader.java:404)
        at java.util.ServiceLoader$1.next(ServiceLoader.java:480)
        at com.nordstrom.automation.junit.LifecycleHooks.<clinit>(LifecycleHooks.java:45)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:386)
        at sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:401)
Caused by: com.epam.reportportal.exception.InternalReportPortalClientException: Cannot build ReportPortal client
        at com.epam.reportportal.service.ReportPortal$Builder.buildClient(ReportPortal.java:266)
        at com.epam.reportportal.service.ReportPortal$Builder.build(ReportPortal.java:246)
        ... 43 more
Caused by: java.net.MalformedURLException
        at java.net.URL.<init>(URL.java:627)
        at java.net.URL.<init>(URL.java:490)
        at java.net.URL.<init>(URL.java:439)
        at com.epam.reportportal.service.ReportPortal$Builder.defaultClient(ReportPortal.java:297)
        at com.epam.reportportal.service.ReportPortal$Builder.buildClient(ReportPortal.java:259)
        ... 44 more
Caused by: java.lang.NullPointerException
        at java.net.URL.<init>(URL.java:532)
        ... 48 more

2 errors
        at com.google.inject.internal.Errors.throwCreationExceptionIfErrorsExist(Errors.java:470)
        at com.google.inject.internal.InternalInjectorCreator.injectDynamically(InternalInjectorCreator.java:184)
        at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:110)
        at com.google.inject.Guice.createInjector(Guice.java:99)
        at com.google.inject.Guice.createInjector(Guice.java:73)
        at com.google.inject.Guice.createInjector(Guice.java:62)
        at com.epam.reportportal.junit.JUnitInjectorProvider$1.get(JUnitInjectorProvider.java:36)
        at com.epam.reportportal.junit.JUnitInjectorProvider$1.get(JUnitInjectorProvider.java:33)
        at com.google.common.base.Suppliers$NonSerializableMemoizingSupplier.get(Suppliers.java:167)
        at com.epam.reportportal.junit.JUnitInjectorProvider.getInstance(JUnitInjectorProvider.java:41)
        at com.epam.reportportal.junit.ReportPortalListener.<clinit>(ReportPortalListener.java:45)
        ... 15 more
log4j:WARN No appenders could be found for logger (com.epam.reportportal.service.ReportPortal).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
Exception in thread "main" java.util.ServiceConfigurationError: com.nordstrom.automation.junit.ShutdownListener: Provider com.epam.reportportal.junit.ReportPortalListener could not be instantiated
        at java.util.ServiceLoader.fail(ServiceLoader.java:232)
        at java.util.ServiceLoader.access$100(ServiceLoader.java:185)
        at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:384)
        at java.util.ServiceLoader$LazyIterator.next(ServiceLoader.java:404)
        at java.util.ServiceLoader$1.next(ServiceLoader.java:480)
        at com.nordstrom.automation.junit.LifecycleHooks.<clinit>(LifecycleHooks.java:45)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:386)
        at sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:401)
Caused by: java.lang.ExceptionInInitializerError
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at java.lang.Class.newInstance(Class.java:442)
        at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:380)
        ... 9 more
Caused by: com.google.inject.CreationException: Unable to create injector, see the following errors:

1) Error in custom provider, java.lang.NullPointerException
  while locating com.epam.reportportal.junit.JUnitProvider
  at com.epam.reportportal.junit.JUnitListenersModule.configure(JUnitListenersModule.java:31)
  while locating com.epam.reportportal.junit.IListenerHandler
Caused by: java.lang.NullPointerException
        at com.epam.reportportal.junit.JUnitProvider.get(JUnitProvider.java:44)
        at com.epam.reportportal.junit.JUnitProvider.get(JUnitProvider.java:30)
        at com.google.inject.internal.ProviderInternalFactory.provision(ProviderInternalFactory.java:81)
FATAL ERROR in native method: processing of -javaagent failed
        at com.google.inject.internal.BoundProviderFactory.provision(BoundProviderFactory.java:72)
        at com.google.inject.internal.ProviderInternalFactory.circularGet(ProviderInternalFactory.java:61)
        at com.google.inject.internal.BoundProviderFactory.get(BoundProviderFactory.java:62)
        at com.google.inject.internal.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:46)
        at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1092)
        at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
        at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:194)
        at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:41)
        at com.google.inject.internal.InternalInjectorCreator$1.call(InternalInjectorCreator.java:205)
        at com.google.inject.internal.InternalInjectorCreator$1.call(InternalInjectorCreator.java:199)
        at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1085)
        at com.google.inject.internal.InternalInjectorCreator.loadEagerSingletons(InternalInjectorCreator.java:199)
        at com.google.inject.internal.InternalInjectorCreator.injectDynamically(InternalInjectorCreator.java:180)
        at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:110)
        at com.google.inject.Guice.createInjector(Guice.java:99)
        at com.google.inject.Guice.createInjector(Guice.java:73)
        at com.google.inject.Guice.createInjector(Guice.java:62)
        at com.epam.reportportal.junit.JUnitInjectorProvider$1.get(JUnitInjectorProvider.java:36)
        at com.epam.reportportal.junit.JUnitInjectorProvider$1.get(JUnitInjectorProvider.java:33)
        at com.google.common.base.Suppliers$NonSerializableMemoizingSupplier.get(Suppliers.java:167)
        at com.epam.reportportal.junit.JUnitInjectorProvider.getInstance(JUnitInjectorProvider.java:41)
        at com.epam.reportportal.junit.ReportPortalListener.<clinit>(ReportPortalListener.java:45)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at java.lang.Class.newInstance(Class.java:442)
        at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:380)
        at java.util.ServiceLoader$LazyIterator.next(ServiceLoader.java:404)
        at java.util.ServiceLoader$1.next(ServiceLoader.java:480)
        at com.nordstrom.automation.junit.LifecycleHooks.<clinit>(LifecycleHooks.java:45)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:386)
        at sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:401)
```
2) Error injecting method, com.epam.reportportal.exception.InternalReportPortalClientException: 
```
Cannot build ReportPortal client
  at com.epam.reportportal.junit.JUnitProvider.setReportPortalService(JUnitProvider.java:39)
  while locating com.epam.reportportal.junit.JUnitProvider
  at com.epam.reportportal.junit.JUnitListenersModule.configure(JUnitListenersModule.java:31)
  while locating com.epam.reportportal.junit.IListenerHandler
Caused by: com.epam.reportportal.exception.InternalReportPortalClientException: Cannot build ReportPortal client
        at com.epam.reportportal.service.ReportPortal$Builder.build(ReportPortal.java:250)
        at com.epam.reportportal.junit.JUnitProvider.setReportPortalService(JUnitProvider.java:39)
        at com.epam.reportportal.junit.JUnitProvider$$FastClassByGuice$$c0d4f1fb.invoke(<generated>)
        at com.google.inject.internal.SingleMethodInjector$1.invoke(SingleMethodInjector.java:54)
        at com.google.inject.internal.SingleMethodInjector.inject(SingleMethodInjector.java:89)
        at com.google.inject.internal.MembersInjectorImpl.injectMembers(MembersInjectorImpl.java:132)
        at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:120)
        at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:90)
        at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:268)
        at com.google.inject.internal.BoundProviderFactory.get(BoundProviderFactory.java:61)
        at com.google.inject.internal.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:46)
        at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1092)
        at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
        at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:194)
        at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:41)
        at com.google.inject.internal.InternalInjectorCreator$1.call(InternalInjectorCreator.java:205)
        at com.google.inject.internal.InternalInjectorCreator$1.call(InternalInjectorCreator.java:199)
        at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1085)
        at com.google.inject.internal.InternalInjectorCreator.loadEagerSingletons(InternalInjectorCreator.java:199)
        at com.google.inject.internal.InternalInjectorCreator.injectDynamically(InternalInjectorCreator.java:180)
        at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:110)
        at com.google.inject.Guice.createInjector(Guice.java:99)
        at com.google.inject.Guice.createInjector(Guice.java:73)
        at com.google.inject.Guice.createInjector(Guice.java:62)
        at com.epam.reportportal.junit.JUnitInjectorProvider$1.get(JUnitInjectorProvider.java:36)
        at com.epam.reportportal.junit.JUnitInjectorProvider$1.get(JUnitInjectorProvider.java:33)
        at com.google.common.base.Suppliers$NonSerializableMemoizingSupplier.get(Suppliers.java:167)
        at com.epam.reportportal.junit.JUnitInjectorProvider.getInstance(JUnitInjectorProvider.java:41)
        at com.epam.reportportal.junit.ReportPortalListener.<clinit>(ReportPortalListener.java:45)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at java.lang.Class.newInstance(Class.java:442)
        at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:380)
        at java.util.ServiceLoader$LazyIterator.next(ServiceLoader.java:404)
        at java.util.ServiceLoader$1.next(ServiceLoader.java:480)
        at com.nordstrom.automation.junit.LifecycleHooks.<clinit>(LifecycleHooks.java:45)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:386)
        at sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:401)
Caused by: com.epam.reportportal.exception.InternalReportPortalClientException: Cannot build ReportPortal client
        at com.epam.reportportal.service.ReportPortal$Builder.buildClient(ReportPortal.java:266)
        at com.epam.reportportal.service.ReportPortal$Builder.build(ReportPortal.java:246)
        ... 43 more
Caused by: java.net.MalformedURLException
        at java.net.URL.<init>(URL.java:627)
        at java.net.URL.<init>(URL.java:490)
        at java.net.URL.<init>(URL.java:439)
        at com.epam.reportportal.service.ReportPortal$Builder.defaultClient(ReportPortal.java:297)
        at com.epam.reportportal.service.ReportPortal$Builder.buildClient(ReportPortal.java:259)
        ... 44 more
Caused by: java.lang.NullPointerException
        at java.net.URL.<init>(URL.java:532)
        ... 48 more

2 errors
        at com.google.inject.internal.Errors.throwCreationExceptionIfErrorsExist(Errors.java:470)
        at com.google.inject.internal.InternalInjectorCreator.injectDynamically(InternalInjectorCreator.java:184)
        at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:110)
        at com.google.inject.Guice.createInjector(Guice.java:99)
        at com.google.inject.Guice.createInjector(Guice.java:73)
        at com.google.inject.Guice.createInjector(Guice.java:62)
        at com.epam.reportportal.junit.JUnitInjectorProvider$1.get(JUnitInjectorProvider.java:36)
        at com.epam.reportportal.junit.JUnitInjectorProvider$1.get(JUnitInjectorProvider.java:33)
        at com.google.common.base.Suppliers$NonSerializableMemoizingSupplier.get(Suppliers.java:167)
        at com.epam.reportportal.junit.JUnitInjectorProvider.getInstance(JUnitInjectorProvider.java:41)
        at com.epam.reportportal.junit.ReportPortalListener.<clinit>(ReportPortalListener.java:45)
        ... 15 more
Process 'Gradle Test Executor 3' finished with non-zero exit value 134
org.gradle.process.internal.ExecException: Process 'Gradle Test Executor 3' finished with non-zero exit value 134
        at org.gradle.process.internal.DefaultExecHandle$ExecResultImpl.assertNormalExitValue(DefaultExecHandle.java:395)
        at org.gradle.process.internal.worker.DefaultWorkerProcess.onProcessStop(DefaultWorkerProcess.java:138)
        at org.gradle.process.internal.worker.DefaultWorkerProcess.access$000(DefaultWorkerProcess.java:41)
        at org.gradle.process.internal.worker.DefaultWorkerProcess$1.executionFinished(DefaultWorkerProcess.java:91)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
        at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
        at org.gradle.internal.event.AbstractBroadcastDispatch.dispatch(AbstractBroadcastDispatch.java:42)
        at org.gradle.internal.event.BroadcastDispatch$SingletonDispatch.dispatch(BroadcastDispatch.java:230)
        at org.gradle.internal.event.BroadcastDispatch$SingletonDispatch.dispatch(BroadcastDispatch.java:149)
        at org.gradle.internal.event.ListenerBroadcast.dispatch(ListenerBroadcast.java:140)
        at org.gradle.internal.event.ListenerBroadcast.dispatch(ListenerBroadcast.java:37)
        at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
        at com.sun.proxy.$Proxy76.executionFinished(Unknown Source)
        at org.gradle.process.internal.DefaultExecHandle.setEndStateInfo(DefaultExecHandle.java:212)
        at org.gradle.process.internal.DefaultExecHandle.finished(DefaultExecHandle.java:340)
        at org.gradle.process.internal.ExecHandleRunner.completed(ExecHandleRunner.java:102)
        at org.gradle.process.internal.ExecHandleRunner.run(ExecHandleRunner.java:82)
        at org.gradle.internal.operations.CurrentBuildOperationPreservingRunnable.run(CurrentBuildOperationPreservingRunnable.java:42)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
        at java.lang.Thread.run(Thread.java:748)`
```

Our current "workaround" is to produce a properties file in every project with the following required properties:

```properties
rp.enabled=false
rp.endpoint=http://place_holder.com:8080
rp.project=place_holder
rp.launch=place_holder
rp.uuid=place_holder
```

**Comment by sspieker-cc** [comment]
Version Specifics:
Logger-log4j: 4.0.1
logger-java-logback: 4.0.0
agent-java-junit: 4.1.8
Client-java: 4.0.12
commons-model: 4.2.0

**Comment by evjlobanova** [comment]
@HardNorth if property file is not found, please disable ReportPortal

**Comment by sspieker-cc** [comment]
We would like to have THAT suggestion to be the default behavior for the tool, however we are finding that it is ENABLED by default.

**Comment by DzmitryHumianiuk** [comment]
@sspieker-cc sure, we will try to implement this as default behavior.

the only issue i see at the moment is that java client also reads environment variables and command line variables during the start.
this should be handled properly, and not to disable environment/cli variables usage

**Comment by sspieker-cc** [comment]
I agree that the behavior should be managed and handled based on the input whether it be by properties file, JVM parameters or ENV variables; the default assumption should be that the reporting be disabled (as if the rp.enabled property is passed with a false value).  The RP functionality should be "forced" on using one of the supported input values.  This would help to keep the developer's machines from reporting on every single build/test cycle.  We would prefer to have only CI builds to report and allow for the CI pipeline to define the values appropriate for each project being processed.

Thanks again!

**Comment by HardNorth** [comment]
Well, we've been living with that for years. So I don't see an rush here. The fix most likely will be release in 5.1 agents.

**Comment by DzmitryHumianiuk** [comment]
@sspieker-cc 
that's quite easy to handle:

1. create properties file with `rp.enable = false`, upload it to you code base and into repositories by default
2. for the CI executions, just add `-Drp.enable = true` in command line.

this will guarantee Disabled reporting for local/developer runs.
and will guarantee Enabled reporting for CI env.

**Comment by dagansandler** [comment]
I'd like to chime in here and claim that the default general behavior for the agent should be disabled unless explicitly enabled.

This breaks the current default behavior, **but** makes much more sense - we almost always include the reportportal agents on our classpath - whether it's testng, junit, or our internal framework's custom agent, but only want to enable it in specific flows, and in those flows we have to provide uuid, endpoint, project name, etc. anyway! so adding the explicit `enable=true` is a no brainer in such case.
Adding `enable=false` however in every flow where we do not want to pass these parameters and report to the service... well... that doesn't make a lot of sense.

**Comment by DzmitryHumianiuk** [comment]
Thank you guys, looks like i've got your point.

According to topic-starter @sspieker-cc 
and @dagansandler, my assumption is that next approach can fit both cases.

Still if we leave `enable=true` by default,
we can control it over `uuid`+`endpoint`+`project`+`launch`.
if something missing from combination, and agent can't establish connection, then it will drop few lines in console, and ignore execution.

Please confirm if it makes sense for both of you.

**Comment by HardNorth** [comment]
Fixed in:
https://github.com/reportportal/client-java/releases/tag/5.0.11
