### ISSUE TITLE
Null check in @Step annotation

### ISSUE THREAD

**Issue by Zahorodnii** [reportportal/client-java#73]
If we use @Step annotation without parameters injection, than StepAspect checking method parameter on null value.

**Example:**

`@Step("Some example")`
void m1(String param) { }

m1(null) -> java.lang.NullPointerException: null value in entry

`@Step("Some {param} example")`
void m2(String param) { }

m2(null) -> java.lang.NullPointerException: null value in entry

In second case it's ok, but for first case it's bad.

My stack trace:
``` java
java.lang.NullPointerException: null value in entry: integrableComponentType=null
    at rp.com.google.common.collect.CollectPreconditions.checkEntryNotNull(CollectPreconditions.java:32)
    at rp.com.google.common.collect.ImmutableMap.entryOf(ImmutableMap.java:176)
    at rp.com.google.common.collect.ImmutableMap$Builder.put(ImmutableMap.java:285)
    at com.epam.reportportal.aspect.StepNameUtils.createParamsMapping(StepNameUtils.java:70)
    at com.epam.reportportal.aspect.StepNameUtils.getStepName(StepNameUtils.java:52)
    at com.epam.reportportal.aspect.StepRequestUtils.buildStartStepRequest(StepRequestUtils.java:45)
    at com.epam.reportportal.aspect.StepAspect.startNestedStep(StepAspect.java:83)
    at como.ui.model.components.hub2.ModalComponent.cancel(ModalComponent.java:27)
    at como.ui.model.components.hub2.ModalComponent.cancel_aroundBody4(ModalComponent.java:33)
    at como.ui.model.components.hub2.ModalComponent.cancel_aroundBody5$advice(ModalComponent.java:18)
    at como.ui.model.components.hub2.ModalComponent.cancel(ModalComponent.java:1)
    at como.ui.hub2.MemberProfileTests.shouldSearchMemberByFirstAndLastNames(MemberProfileTests.java:111)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
    at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:597)
    at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
    at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
    at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
    at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
    at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
    at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
    at java.util.ArrayList.forEach(ArrayList.java:1257)
    at org.testng.TestRunner.privateRun(TestRunner.java:766)
    at org.testng.TestRunner.run(TestRunner.java:587)
    at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
    at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
    at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
    at org.testng.SuiteRunner.run(SuiteRunner.java:286)
    at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
    at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
    at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
    at org.testng.TestNG.runSuitesLocally(TestNG.java:1109)
    at org.testng.TestNG.runSuites(TestNG.java:1039)
    at org.testng.TestNG.run(TestNG.java:1007)
    at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
    at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:110)
```

**Comment by DzmitryHumianiuk** [comment]
@Zahorodnii good catch :)

**Comment by evjlobanova** [comment]
@Yumfriez could you please link a pr to this issue?
